# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContractTemplate.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Contract_Template_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(400, 300)
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)

        self.font = QtGui.QFont()
        self.font.setFamily("MS Shell Dlg 2")
        self.font.setPointSize(7)

        self.gridLayout_5 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblSource = QtWidgets.QLabel(self.groupBox)
        self.lblSource.setObjectName("lblSource")
        self.gridLayout.addWidget(self.lblSource, 0, 0, 1, 1)
        self.btnOutputFolder = QtWidgets.QPushButton(self.groupBox)
        self.btnOutputFolder.setMinimumSize(QtCore.QSize(20, 20))
        self.btnOutputFolder.setMaximumSize(QtCore.QSize(20, 20))
        self.btnOutputFolder.setObjectName("btnOutputFolder")
        self.gridLayout.addWidget(self.btnOutputFolder, 1, 4, 1, 1)
        self.btnSourceFolder = QtWidgets.QPushButton(self.groupBox)
        self.btnSourceFolder.setMinimumSize(QtCore.QSize(20, 20))
        self.btnSourceFolder.setMaximumSize(QtCore.QSize(20, 20))
        self.btnSourceFolder.setObjectName("btnSourceFolder")
        self.gridLayout.addWidget(self.btnSourceFolder, 0, 4, 1, 1)
        self.leSourceFolder = QtWidgets.QLineEdit(self.groupBox)
        self.leSourceFolder.setReadOnly(True)
        self.leSourceFolder.setFont(self.font)
        self.leSourceFolder.setObjectName("leSourceFolder")
        self.gridLayout.addWidget(self.leSourceFolder, 0, 1, 1, 3)
        self.lblOutput = QtWidgets.QLabel(self.groupBox)
        self.lblOutput.setObjectName("lblOutput")
        self.gridLayout.addWidget(self.lblOutput, 1, 0, 1, 1)
        self.leOutputFolder = QtWidgets.QLineEdit(self.groupBox)
        self.leOutputFolder.setReadOnly(True)
        self.leOutputFolder.setFont(self.font)
        self.leOutputFolder.setObjectName("leOutputFolder")
        self.gridLayout.addWidget(self.leOutputFolder, 1, 1, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self._lblProgress = QtWidgets.QLabel(Dialog)
        self._lblProgress.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self._lblProgress.setFont(font)
        self._lblProgress.setAlignment(QtCore.Qt.AlignCenter)
        self._lblProgress.setObjectName("_lblProgress")
        self.verticalLayout.addWidget(self._lblProgress)
        self._progressBar = QtWidgets.QProgressBar(Dialog)
        self._progressBar.setProperty("value", 100)
        self._progressBar.setTextVisible(False)
        self._progressBar.setObjectName("_progressBar")
        self.verticalLayout.addWidget(self._progressBar)
        self.gridLayout_2.addLayout(self.verticalLayout, 5, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblKeyword = QtWidgets.QLabel(self.groupBox_2)
        self.lblKeyword.setObjectName("lblKeyword")
        self.gridLayout_3.addWidget(self.lblKeyword, 0, 1, 1, 1)
        self.leKeyword = QtWidgets.QLineEdit(self.groupBox_2)
        self.leKeyword.setClearButtonEnabled(True)
        self.leKeyword.setObjectName("leKeyword")
        self.gridLayout_3.addWidget(self.leKeyword, 0, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbtnDebit = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtnDebit.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.rbtnDebit.setChecked(True)
        self.rbtnDebit.setObjectName("rbtnDebit")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rbtnDebit)
        self.horizontalLayout.addWidget(self.rbtnDebit)
        self.rbtnCredit = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtnCredit.setObjectName("rbtnCredit")
        self.buttonGroup.addButton(self.rbtnCredit)
        self.horizontalLayout.addWidget(self.rbtnCredit)
        self.rbtnAll = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtnAll.setObjectName("rbtnAll")
        self.buttonGroup.addButton(self.rbtnAll)
        self.horizontalLayout.addWidget(self.rbtnAll)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(Dialog)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout_2.addWidget(self.btnGenerate, 3, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Contract Type Template"))
        self.groupBox.setTitle(_translate("Dialog", "Folders"))
        self.lblSource.setText(_translate("Dialog", "Source File:"))
        self.btnOutputFolder.setText(_translate("Dialog", "..."))
        self.btnSourceFolder.setText(_translate("Dialog", "..."))
        self.lblOutput.setText(_translate("Dialog", "Output Folder:"))
        self._lblProgress.setText(_translate("Dialog", "Progress"))
        self.groupBox_2.setTitle(_translate("Dialog", "Options"))
        self.lblKeyword.setText(_translate("Dialog", "Keyword:"))
        self.rbtnDebit.setText(_translate("Dialog", "Debit"))
        self.rbtnCredit.setText(_translate("Dialog", "Credit"))
        self.rbtnAll.setText(_translate("Dialog", "All"))
        self.btnGenerate.setText(_translate("Dialog", "Generate"))

    def updateWindowTitle(self, Dialog, title):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", title))